/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module arithmetic_3 (
    input [7:0] a,
    input [7:0] b,
    input [1:0] c,
    output reg [10:0] out
  );
  
  
  
  wire [11-1:0] M_adder_out;
  reg [8-1:0] M_adder_a;
  reg [8-1:0] M_adder_b;
  reg [1-1:0] M_adder_c;
  adder_7 adder (
    .a(M_adder_a),
    .b(M_adder_b),
    .c(M_adder_c),
    .out(M_adder_out)
  );
  
  wire [8-1:0] M_mult_out;
  reg [8-1:0] M_mult_a;
  reg [8-1:0] M_mult_b;
  mult_8 mult (
    .a(M_mult_a),
    .b(M_mult_b),
    .out(M_mult_out)
  );
  
  always @* begin
    M_adder_a = a;
    M_adder_b = b;
    M_adder_c = c[0+0-:1];
    M_mult_a = a;
    M_mult_b = b;
    if (c[1+0-:1]) begin
      out[0+7-:8] = M_mult_out;
    end else begin
      out[0+7-:8] = M_adder_out[0+7-:8];
    end
    out[8+2-:3] = M_adder_out[8+2-:3];
  end
endmodule
