/*
   This file was generated automatically by the Mojo IDE version B1.3.2.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_11 (
    input [7:0] a,
    input [7:0] b,
    input [1:0] c,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    
    case (c[0+1-:2])
      1'h0: begin
        out = a << b;
      end
      1'h1: begin
        out = a >> b;
      end
      2'h2: begin
        out = $signed(a) <<< b;
      end
      2'h3: begin
        out = $signed(a) >>> b;
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
