/*
   This file was generated automatically by the Mojo IDE version B1.3.2.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = DIGIT_BITS
*/
module decoder_8 (
    input [1:0] in,
    output reg [3:0] out
  );
  
  localparam WIDTH = 2'h2;
  
  
  integer i;
  
  always @* begin
    for (i = 1'h0; i < 3'h4; i = i + 1) begin
      if (in == i) begin
        out[(i)*1+0-:1] = 1'h1;
      end else begin
        out[(i)*1+0-:1] = 1'h0;
      end
    end
  end
endmodule
